# Generated by Django 4.2 on 2023-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
